kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azure-file-claim
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: azure-file
