apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-file
  # The label is used for matching the exact claim
  labels:
    usage: azure-file
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  azureFile:
    # Replace with your secret name
    secretName: azure-secret
    # Replace with correct storage share name
    shareName: data
    # In case the secret is stored in a different namespace
    #shareNamespace: default
    readOnly: false
